spring:
  application:
    name: GenAiQuestionApp
  profiles:
    active: test # 현재 활성화된 환경 (개발: test || 운영: prod)
devtools:
  restart:
    enabled: true
server:
  port: 8080 # 애플리케이션 포트 설정, 기본은 8080
  address: 0.0.0.0 # 모든 IP 주소에서 접근 허용
logging:
  file:
    path: logs # log file
jwt:
  secret: sC/o5UiWPOR8ObUuep12mhhvdanGRTKw09Ey4weX8r3XMu3Rve5VjnalBuLZhsTqXm/bS/TDLZAkaihkStvp8Q==
  expiration-ms: 3600000
cors:
  allowed-origins: http://localhost:5173
ai:
  problem:
    generator:
      url: http://127.0.0.1:8000/problems/generate