myboot:
  name: Prod Env
logging:
  level:
    com:
      basic:
        myspringboot: debug
spring:
  datasource:
    url: jdbc:mariadb://jlpt-db:3306/${MYSQL_DATABASE}?characterEncoding=utf8mb4&connectionCollation=utf8mb4_unicode_ci&useUnicode=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        connection.characterEncoding: utf8mb4
        connection.useUnicode: true
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
    

