myboot:
  name: Prod Env
logging:
  level:
    com:
      basic:
        myspringboot: debug
spring:
  datasource:
    url: jdbc:mariadb://jlpt-db:3306/${MYSQL_DATABASE}?characterEncoding=utf8mb4&connectionCollation=utf8mb4_general_ci&useUnicode=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  sql:
    init:
      mode: never # <-- 스프링 부트의 내장 SQL 초기화 기능 비활성화
  flyway:
    locations: classpath:db/migration # 마이그레이션 스크립트가 위치할 경로
    enabled: true # Flyway 활성화
    baseline-on-migrate: true
    
