spring:
  application:
    name: GenAiQuestionApp
  profiles:
    active: test # 현재 활성화된 환경 - 개발 환경에 따라 수정하세요
devtools:
  restart:
    enabled: true # 기본 true
server:
  port: 8080 # 애플리케이션 포트 설정, 기본은 8080
  address: 0.0.0.0 # 모든 IP 주소에서 접근 허용
logging:
  file:
    path: logs # log file
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 3600000
cors:
  allowed-origins: http://localhost:5173