myboot:
  name: Prod Env
logging:
  level:
    com:
      basic:
        myspringboot: debug
spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/jlpt_question_db
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
